apiVersion: v1
data:
  default-values.yaml: |
    imagePullSecrets:
      - name: docker-io-pull-secret
    wkp-ui:
      image:
        pullSecrets:
          - docker-io-pull-secret
    dbConfig:
      databaseType: sqlite
    sqliteConfig:
      persistentVolumeClaim: true
    agentTemplate:
      natsURL: 18.197.146.152:31490
    nats:
      client:
        service:
          nodePort: 31490
    config:
      capi:
        repositoryURL: https://github.com/saeedfazal/mccp-testing
        baseBranch: main
    nginx-ingress-controller:
      service:
        nodePorts:
          http:
            30080
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: weave-gitops-enterprise-mccp-chart-defaultvalues
  namespace: wego-system
